web:
  image: oydeu/oyd-donate
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - donate_db
  ports:
    - "4700:3000"

donate_db:
  image: postgres:9.4.5
  volumes:
    - docker-postgres:/var/lib/postgresql/data
